/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    gallery: Gallery;
    testimonials: Testimonial;
    faq: Faq;
    statistics: Statistic;
    'value-propositions': ValueProposition;
    timeline: Timeline;
    certificates: Certificate;
    'social-links': SocialLink;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    statistics: StatisticsSelect<false> | StatisticsSelect<true>;
    'value-propositions': ValuePropositionsSelect<false> | ValuePropositionsSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en' | 'kk') | ('ru' | 'en' | 'kk')[];
  globals: {
    person: Person;
    'home-page': HomePage;
    'about-page': AboutPage;
    'financial-page': FinancialPage;
    'travel-page': TravelPage;
    'contact-page': ContactPage;
    'legal-page': LegalPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    person: PersonSelect<false> | PersonSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'financial-page': FinancialPageSelect<false> | FinancialPageSelect<true>;
    'travel-page': TravelPageSelect<false> | TravelPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'legal-page': LegalPageSelect<false> | LegalPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ru' | 'en' | 'kk';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Два направления работы. Здесь добавляются новые туры, курсы и лагеря.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Задаётся один раз. Связывает запись со страницей сайта.
   */
  projectId: 'financial' | 'travel';
  /**
   * Видно только в админ-панели, чтобы отличать записи в списке.
   */
  title: string;
  name: string;
  /**
   * Одно предложение. Показывается на карточке проекта на главной.
   */
  tagline: string;
  /**
   * Каждая запись — отдельный абзац на странице проекта.
   */
  description?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Крупное фото в шапке страницы проекта. Рекомендуемый размер: 1920×1080.
   */
  heroImage: number | Media;
  /**
   * Необязательно. Рекомендуемый размер: 240×80.
   */
  logo?: (number | null) | Media;
  offerings?:
    | {
        title: string;
        description: string;
        /**
         * Небольшой значок рядом с названием программы.
         */
        icon?: ('compass' | 'languages' | 'tent' | 'wallet' | 'trending-up' | 'star') | null;
        /**
         * Рекомендуемый размер: 1200×900.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  contacts?: {
    /**
     * Только цифры, в международном формате, без «+» и пробелов. Например: 77011234567
     */
    whatsappPhone?: string | null;
    /**
     * Этот текст автоматически подставляется в поле ввода, когда человек нажимает кнопку WhatsApp.
     */
    whatsappMessage?: string | null;
    /**
     * Без символа «@». Например: meruert_tours
     */
    telegramUsername?: string | null;
    /**
     * Без символа «@».
     */
    instagramUsername?: string | null;
    email?: string | null;
  };
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Все изображения сайта. Загрузите файл и добавьте описание.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Коротко опишите, что на фото. Это читают программы для незрячих и поисковые системы. Например: «Меруерт проводит урок финансовой грамотности».
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Фотографии для галереи на главной и на страницах проектов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Видно только в админ-панели, чтобы находить фото в списке.
   */
  title: string;
  /**
   * Рекомендуемый размер: не менее 1600px по длинной стороне.
   */
  image: number | Media;
  /**
   * Необязательно. Показывается под фото.
   */
  caption?: string | null;
  /**
   * Определяет, на какой странице показывается эта запись.
   */
  project: 'shared' | 'financial' | 'travel';
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Отзывы клиентов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Не переводится — имя пишется одинаково на всех языках.
   */
  authorName: string;
  /**
   * Например: «Участница курса по финансовой грамотности». Необязательно.
   */
  authorRole?: string | null;
  quote: string;
  /**
   * Рекомендуемый размер: 200×200.
   */
  avatar?: (number | null) | Media;
  /**
   * От 1 до 5 звёзд. Необязательно — без оценки звёзды не показываются.
   */
  rating?: number | null;
  /**
   * Определяет, на какой странице показывается эта запись.
   */
  project: 'shared' | 'financial' | 'travel';
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Частые вопросы. Показываются на главной и на страницах проектов.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Короткая версия вопроса — видна только в админ-панели.
   */
  questionTitle: string;
  question: string;
  answer: string;
  /**
   * Определяет, на какой странице показывается эта запись.
   */
  project: 'shared' | 'financial' | 'travel';
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Цифры, которые считаются вверх при прокрутке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics".
 */
export interface Statistic {
  id: number;
  /**
   * Видно только в админ-панели.
   */
  title: string;
  /**
   * Только цифры. Знаки «+» или «%» добавьте в полях ниже.
   */
  value: number;
  /**
   * Например: «≈». Необязательно.
   */
  prefix?: string | null;
  /**
   * Например: «+» или «%». Необязательно.
   */
  suffix?: string | null;
  /**
   * Что означает это число. Например: «учеников».
   */
  label: string;
  placement: 'home' | 'about';
  /**
   * Определяет, на какой странице показывается эта запись.
   */
  project: 'shared' | 'financial' | 'travel';
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Карточки с иконкой и описанием. Поле «Где показывать» определяет раздел сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-propositions".
 */
export interface ValueProposition {
  id: number;
  /**
   * Видно только в админ-панели.
   */
  title: string;
  placement: 'why-choose-me' | 'mission-values' | 'financial-formats' | 'financial-benefits';
  icon: 'star' | 'compass' | 'wallet' | 'trending-up' | 'languages' | 'tent' | 'check' | 'info';
  heading: string;
  description: string;
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ключевые этапы пути. Показываются на странице «Обо мне».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  /**
   * Например: «2019» или «2019–2021». Не переводится.
   */
  date: string;
  title: string;
  /**
   * Необязательно.
   */
  description?: string | null;
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Сертификаты и дипломы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  /**
   * Видно только в админ-панели.
   */
  title: string;
  name: string;
  /**
   * Необязательно.
   */
  issuer?: string | null;
  /**
   * Рекомендуемый размер: 800×600.
   */
  image: number | Media;
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ссылки на соцсети в подвале сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  /**
   * Видно только в админ-панели.
   */
  title: string;
  platform: 'instagram' | 'telegram' | 'whatsapp' | 'email' | 'phone';
  /**
   * Полный адрес, начиная с https:// — например https://instagram.com/имя. Для почты: mailto:адрес
   */
  url: string;
  /**
   * Определяет, на какой странице показывается эта запись.
   */
  project: 'shared' | 'financial' | 'travel';
  /**
   * Чем меньше число, тем выше запись в списке.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Пользователи, которые могут входить в админ-панель.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Показывается в интерфейсе админ-панели.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'statistics';
        value: number | Statistic;
      } | null)
    | ({
        relationTo: 'value-propositions';
        value: number | ValueProposition;
      } | null)
    | ({
        relationTo: 'timeline';
        value: number | Timeline;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'social-links';
        value: number | SocialLink;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  projectId?: T;
  title?: T;
  name?: T;
  tagline?: T;
  description?:
    | T
    | {
        text?: T;
        id?: T;
      };
  heroImage?: T;
  logo?: T;
  offerings?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        whatsappPhone?: T;
        whatsappMessage?: T;
        telegramUsername?: T;
        instagramUsername?: T;
        email?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  authorRole?: T;
  quote?: T;
  avatar?: T;
  rating?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  questionTitle?: T;
  question?: T;
  answer?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics_select".
 */
export interface StatisticsSelect<T extends boolean = true> {
  title?: T;
  value?: T;
  prefix?: T;
  suffix?: T;
  label?: T;
  placement?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-propositions_select".
 */
export interface ValuePropositionsSelect<T extends boolean = true> {
  title?: T;
  placement?: T;
  icon?: T;
  heading?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  date?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  name?: T;
  issuer?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  title?: T;
  platform?: T;
  url?: T;
  project?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Имя, биография, портрет и город. Используется по всему сайту.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person".
 */
export interface Person {
  id: number;
  /**
   * Показывается в шапке, подвале, заголовках вкладок и в данных для поисковых систем. Не переводится.
   */
  fullName: string;
  /**
   * Одна строка под именем. Например: «Финансовый педагог и автор путешествий».
   */
  tagline: string;
  /**
   * Каждая запись — отдельный абзац.
   */
  biography?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Главное фото на первом экране. Рекомендуемый размер: 1200×1500 (вертикальный).
   */
  photo: number | Media;
  /**
   * Короткие строки рядом с биографией. Например: «500+ учеников».
   */
  credentials?:
    | {
        label: string;
        /**
         * Например: «2019». Необязательно.
         */
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Например: «Астана, Казахстан».
   */
  location: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовки и подписи на главной странице.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * Крупная фраза на первом экране. Лучше всего читается до 60 символов.
     */
    headline: string;
    /**
     * 1–2 предложения под заголовком.
     */
    intro: string;
    primaryCtaLabel: string;
    secondaryCtaLabel: string;
    scrollIndicatorLabel: string;
  };
  aboutPreview: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  projects: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  /**
   * Например: «Подробнее» — далее подставляется название проекта.
   */
  projectsCardCtaLabel: string;
  whyChooseMe: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  statistics: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  testimonials: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  galleryPreview: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  faqPreview: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  cta: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовки на странице «Обо мне».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow: string;
    headline: string;
    intro: string;
    primaryCtaLabel: string;
    secondaryCtaLabel: string;
    scrollIndicatorLabel: string;
  };
  biography: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  missionValues: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  timeline: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  achievements: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  certificates: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  gallery: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  cta: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовки на странице «Финансовая грамотность».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-page".
 */
export interface FinancialPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    subtitle?: string | null;
    intro: string;
  };
  about: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  services: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  learningFormats: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  benefits: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  successStories: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  gallery: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  faq: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  cta: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовки на странице «Туры и курсы».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-page".
 */
export interface TravelPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    subtitle?: string | null;
    intro: string;
  };
  about: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  programs: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  tours: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  languageCourses: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  camps: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  gallery: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  reviews: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  faq: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  cta: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Тексты на странице «Контакты».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  channelsHeading: {
    /**
     * Короткая метка над заголовком, например «Обо мне». Необязательно.
     */
    eyebrow?: string | null;
    heading: string;
    /**
     * 1–2 предложения под заголовком. Необязательно.
     */
    subtitle?: string | null;
  };
  /**
   * Кнопка WhatsApp на карточке каждого проекта. Например: «Написать в WhatsApp».
   */
  primaryActionLabel: string;
  locationLabel: string;
  workingHoursLabel: string;
  /**
   * Например: «Пн–Пт, 10:00–18:00».
   */
  workingHours: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Политика конфиденциальности. ВНИМАНИЕ: сейчас здесь шаблонный текст — замените его перед запуском сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page".
 */
export interface LegalPage {
  id: number;
  title: string;
  lastUpdatedLabel: string;
  /**
   * Показывается на странице и форматируется под язык посетителя.
   */
  lastUpdated: string;
  intro: string;
  sections?:
    | {
        heading: string;
        body?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Название сайта в поиске, описание, картинка для соцсетей и подвал.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Показывается во вкладке браузера и в результатах поиска. Оптимально до 60 символов.
   */
  defaultTitle: string;
  /**
   * Текст под ссылкой в результатах поиска. Оптимально 120–160 символов.
   */
  defaultDescription: string;
  /**
   * Показывается, когда ссылку на сайт отправляют в WhatsApp, Telegram или соцсети. Рекомендуемый размер: 1200×630.
   */
  defaultOgImage: number | Media;
  /**
   * Год подставляется автоматически, его указывать не нужно.
   */
  footerOwnerName: string;
  /**
   * Например: «Все права защищены».
   */
  footerCopyrightNotice: string;
  /**
   * Заголовки колонок и подписи ссылок. Адреса страниц выбираются из готового списка.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: '/' | '/about' | '/financial-literacy' | '/tours-and-courses' | '/contact' | '/privacy-policy';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  navAboutLabel: string;
  navContactLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person_select".
 */
export interface PersonSelect<T extends boolean = true> {
  fullName?: T;
  tagline?: T;
  biography?:
    | T
    | {
        text?: T;
        id?: T;
      };
  photo?: T;
  credentials?:
    | T
    | {
        label?: T;
        year?: T;
        id?: T;
      };
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        intro?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        scrollIndicatorLabel?: T;
      };
  aboutPreview?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  projects?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  projectsCardCtaLabel?: T;
  whyChooseMe?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  statistics?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  galleryPreview?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  faqPreview?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        intro?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        scrollIndicatorLabel?: T;
      };
  biography?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  missionValues?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  timeline?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  achievements?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  certificates?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-page_select".
 */
export interface FinancialPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
        intro?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  learningFormats?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  successStories?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-page_select".
 */
export interface TravelPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
        intro?: T;
      };
  about?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  programs?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  tours?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  languageCourses?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  camps?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  reviews?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  channelsHeading?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtitle?: T;
      };
  primaryActionLabel?: T;
  locationLabel?: T;
  workingHoursLabel?: T;
  workingHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page_select".
 */
export interface LegalPageSelect<T extends boolean = true> {
  title?: T;
  lastUpdatedLabel?: T;
  lastUpdated?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  footerOwnerName?: T;
  footerCopyrightNotice?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  navAboutLabel?: T;
  navContactLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}